name: Publish Docker image for local-env 

# ToDo should it be triggered only as part of an open PR?
# currently it triggers for any commit in a FB
on: 
  workflow_call:
      
jobs:
  push_to_registry:
    permissions:
      packages: write
      contents: read
      attestations: write
    uses: Yam1xTest/workflows/.github/workflows/local-env-docker-build-and-push.yml@main
    with: 
      build-args: |
        # this perfectly explains why this is needed https://github.com/strapi/strapi/issues/13889#issuecomment-1516194973
        SERVER_URL=/cms
      prefix: ""
    secrets: inherit
